### PR TITLE
Another demo PR

### PR DESCRIPTION
**Pull request by orangemug**

### CODE REVIEW

**Comment by pathmapper** [comment]
@orangemug why did the last commit (https://github.com/orangemug/editor-ci-test/pull/2/commits/b11897a4e669cbf74cad472dec67b26102d45d7c) not trigger a demo link?

Is there an ignore file somewhere?

**Comment by orangemug** [comment]
@pathmapper so the action will only create one 'demo link' the `unsplash/comment-on-pr` action simply doesn't create it if the same comment already exists. The link never changes and codesandbox just updates the content as the PR branch gets new commits.

**Comment by orangemug** [comment]
...there are 2 comments in this issue because I changed the content of the issue text, which was probably confusing :)

**Comment by pathmapper** [comment]
> which was probably confusing :)

At least for me :-)

If I got it right, there's currently no react profiling build.

**Comment by orangemug** [comment]
> If I got it right, there's currently no react profiling build.

Ah yes correct, at the moment it starts a production build as defined by `sandbox.config.json`, I guess we could only output the profiling build to the codesandbox.

For the artifacts we could build more, although we'll need to download those to test them.

Thoughts?

**Comment by pathmapper** [comment]
> I guess we could only output the profiling build to the codesandbox

This would make no sense regarding performance comparisons, right?

> For the artifacts we could build more, although we'll need to download those to test them.

This would be fine. With our current setup I'm not using the profile build often, but it would be nice to have one available for download.

**Comment by orangemug** [comment]
@pathmapper hmmm, I'm not entirely sure what will happen if a user without perms makes a pull request, I assume that the _comment action_ will fail because the `GITHUB_TOKEN` secret doesn't have those perms for that user (as described https://github.com/nyurik/auto_pr_comments_from_forks)

@pathmapper could you fork this repo, change something (just add a comment to the README.md) and make a pull request? Because you don't have access I'm hoping that the CI should run ok 🤞but the comment on PR will fail (I'll look into fixing that afterwards)

**Comment by orangemug** [comment]
Ah no worries @pathmapper I can see that doesn't work now in https://github.com/maputnik/editor/runs/703685686?check_suite_focus=true

**Comment by orangemug** [comment]
Oh actually @pathmapper maybe it is still worth testing that the CI runs, because I have write access to `maputnik/editor`, whereas you won't have any access to this repo. Which is the same as new maputnik contributors.

**Pull request merged**
